# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'RouterManager' do

  pod 'MJExtension', '~> 2.5.16'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'Masonry', '~> 1.0.2'

  target 'RouterManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RouterManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
